db:
  image: postgres
web:
  build: .
  # This runs multiple commands, the first to destroy any processes I left up (oops),
  # and the next to start the rails server fresh
  command: bash -c "rm -f /w8mngr/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/w8mngr
  ports:
    - "3000:3000"
  links:
    - db
  # The below allows us to attach byebug with docker
  # To do so, use these commands to start the docker container:
  # docker-compose up -d
  # docker attach w8mngr_web_1
  stdin_open: true
  tty: true
