branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: w8mngr
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
  RDS_DB_NAME: w8mngr
  RDS_USERNAME: baublet
  RDS_PASSWORD: 12coast12
  RDS_HOSTNAME: w8mngrmaster.ckdhgpwmxgek.us-east-1.rds.amazonaws.com
  RDS_PORT: 5432